-- SQLite
SELECT c.*, COUNT(l.ID) AS 'LOCATIONS'
FROM CUSTOMERS AS c
JOIN LOCATIONS AS l ON c.ID = l.CUSTOMER_ID
GROUP BY c.ID, c.NAME, c.LASTNAME, c.PHONE, c.EMAIL, c.ADRESS, c.CITY, c.STATE, c.BIRTH_DATE
HAVING COUNT(l.ID) >= 2;
